# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f25e3f641c8fa7eee0e29ebc37dbc34831141c97f41c71e394ec1c4056128210e2b8da2e41bc1457d0a2a65c416a29e3d99e3f3a178d267ab6ccb4b66a3f38c1

test:
  secret_key_base: 66d5ad2ee78c9235eed08c663250e9efd195cd84d6081d25961e3d351446d665905dabfbc3462ceee3fa0383da3b54570ccf57574110f17ee3aecc40b839afd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
